<?php
// $Id$

/**
 * @file
 * validate login information from techcenterboise.com and log the user in as
 * a given user.
 * */

 /**
 * Implements hook_permission().
 */
function tcb_auth_client_permission() {
  return array(
    'administer tcb client' => array(
      'title' => t('Administer TCB User Client module'),
      'description' => t('Perform administration tasks for TCB User Client module.'),
    ),
  );
}

 /**
  *Implementation of hook_menu().
  **/
function tcb_auth_client_menu() {
    $items['admin/config/people/tcb']=array(
        'title' => 'TCB User Client Settings',
        'description' => 'TCB User Client Settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tcb_auth_client_admin_settings'),
        'access arguments' => array('administer tcb client'),
    );
    return $items;    
}

/**
 * give the admin settings form
 * */
function tcb_auth_client_admin_settings() {
    $form['tcbclient_uid'] = array(
        '#title' => t('Logged in user name'),
        '#description' => t('When the user logs in, what user on this site do you want them to be logged in as?'),
        '#default_value' => variable_get('tcbclient_uid', ''),
        '#type' => 'textfield',
        '#autocomplete_path' => 'user/autocomplete',
    );
    $form['tcbclient_url'] = array(
        '#title' => t('Server URL'),
        '#description' => t('This is the URL where the TCB authentication server can be found, this requires fully qualified URL.'),
        '#default_value' => variable_get('tcbclient_url', ''),
        '#type' => 'textfield',
    );
    return system_settings_form($form);
}

/**
 * Implementation of hook_form_alter().
 * */
function tcb_auth_client_form_alter(&$form, $form_state, $form_id) {
    switch ($form_id) {
        case 'user_login_block':
            
        case 'user_login':
            array_unshift($form['#validate'], 'tcb_auth_client_login_validate');
            break;
    }
}

/**
 * confirm that the user is either a user on this system, or an authorized
 * user on techcenterboise.com
 * */
function tcb_auth_client_login_validate($form, &$form_state) {
    $form_values = $form_state['values'];
    if ((strpos($form_values['name'], '@techcenterboise.com') !== FALSE) && variable_get('tcbclient_uid', '')) {
        $name = explode('@techcenterboise.com', $form_values['name']);
        $url = variable_get('tcbclient_url') . 'tcbusermanagementserver/authenticate_user/' .  urlencode($name[0]) . '/' . $form_values['pass'];
        $data = drupal_http_request($url);
        $result = $data->data;
        $tokens = array(
            '@username' => $name[0],
        );
        if ($result == 'true') {
            global $user;
            $account = user_load_by_name(array('name' => variable_get('tcbclient_uid', '')));
            $tokens['@this_user'] = $account->name;
            $user = $account;
            watchdog('user_management', '@username has successfully logged in by TCB User Client as user @this_user', $tokens);
            user_login_finalize($form_values);
            drupal_goto('user');
        }
        else {
            watchdog('user_management', '@username has attempted to log in by TCB User Client', $tokens);
        }
    }
}
