<?php
// $Id$

/**
 * @file
 * Provides configuration page to choose a menu to pull items from and create a custom menu using those items.
 */

function company_info_form_system_site_information_settings_alter(&$form, &$form_state) {
  $poweredby_options = array(
    0 => t('Tribute Media'),
    1 => t('Convergo'),
  );
  $form['company_info'] = array(
    '#type' => 'fieldset',
    '#title' => t('Company Information'),
    '#weight' => 1,
  );
  $form['company_info']['desc_text'] = array(
    '#markup' => t('This information will be stored in variables for use in template files.'),
  );
  $form['company_info']['co_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Street Address'),
    '#maxlength' => 128,
    '#default_value' => variable_get('co_address', '123 Main Street'),
    '#required' => TRUE,
  );
  $form['company_info']['co_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#maxlength' => 128,
    '#default_value' => variable_get('co_city', 'Anytown'),
    '#required' => TRUE,
  );
  $form['company_info']['co_state'] = array(
    '#type' => 'textfield',
    '#title' => t('State/Province'),
    '#maxlength' => 128,
    '#default_value' => variable_get('co_state', 'State'),
    '#required' => TRUE,
  );
  $form['company_info']['co_zip'] = array(
    '#type' => 'textfield',
    '#title' => t('Postal Code'),
    '#maxlength' => 10,
    '#default_value' => variable_get('co_zip', '90909'),
    '#required' => TRUE,
  );
  $form['company_info']['co_phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone Number'),
    //'#maxlength' => 12,
    '#default_value' => variable_get('co_phone', '888-828-8282'),
    '#required' => TRUE,
  );
  $form['company_info']['co_phone2'] = array(
          '#type' => 'textfield',
          '#title' => t('Alternate Phone Number'),
          //'#maxlength' => 12,
          '#default_value' => variable_get('co_phone2', ''),
          //'#required' => TRUE,
  ); //Added by Matthew Contos 11JAN2017
    $form['company_info']['co_fax'] = array(
            '#type' => 'textfield',
            '#title' => t('Fax Number'),
            //'#maxlength' => 12,
            '#default_value' => variable_get('co_fax', ''),
            //'#required' => TRUE,
  ); //Added by Matthew Contos 11JAN2017
  $form['attribute_line_info'] = array(
    '#type' => 'fieldset',
    '#title' => t('Attribute Line Information'),
    '#weight' => 2,
  );
  $form['attribute_line_info']['powered_by'] = array(
    '#type' => 'select',
    '#title' => t('Powered by'),
    '#options' => $poweredby_options,
    '#default_value' => variable_get('powered_by', $poweredby_options[0]),
  );
}