<?php
require_once(drupal_get_path('module', 'better_mm') . '/includes/helpers.inc');

/**
 * Gets called after a node has been inserted to database.
 *
 * @param $node
 *   A node object
 *
 * @see hook_node_postsave()
 * @see hook_node_postupdate()
 * @see hook_node_postdelete()
 * @see hook_node_postinsert()
 */
function hook_post_action_bmm_node_postinsert($node) {
  $menu = $node->menu;
  $bmm = variable_get('bmm_menu', '');

  if ($menu['enabled']) {
    $parent = explode(':', $menu['parent']);
    $menu_name = $parent[0];

	// If the menu we're editing is the BMM and if the current node being
	// inserted is at the root level of the menu, add it to the BMM form
	// settings variable
    if ($menu_name == $bmm) {
      if(strpos($menu['parent'], $parent[0] . ':0') !== FALSE) {
        saveToBMMItemSettings($node->menu['link_title'], $node->menu['mlid']);
      }

      $bmm_block_content = bmm_gen_block_html($bmm);
      variable_set('bmm_block_content', $bmm_block_content['html']);
      variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
    }
  }
}

/**
 * Gets called after a node has been updated to database.
 *
 * @param $node
 *   A node object
 *
 * @see hook_node_postsave()
 * @see hook_node_postinsert()
 * @see hook_node_postdelete()
 * @see hook_node_postupdate()
 */
function hook_post_action_bmm_node_postupdate($node) {
  $menu = $node->menu;
  $link_title = strtolower($node->menu['link_title']);
  $link_mlid = $node->menu['mlid'];
  $menu_settings = variable_get('bmm_menu_items_settings');
  $bmm = variable_get('bmm_menu', '');

  if ($menu['enabled']) {
    $parent = explode(':', $menu['parent']);
    $menu_name = $parent[0];

	// If the menu being edited is the BMM and the currently updated node
	// is in the root level of the menu, add a setting for the BMM form
	// settings variable
  if ($menu_name == $bmm) {
	  if(strpos($menu['parent'], $parent[0] . ':0') !== FALSE) {
        if((isset($menu_settings[$link_title])
          && $menu_settings[$link_title]['style'] != 'advanced') ||
          (isset($menu_settings[$link_mlid]) &&
          $menu_settings[$link_mlid]['style'] != 'advanced')) {
          
          saveToBMMItemSettings($node->menu['link_title'], $node->menu['mlid']);
        }
      }

      $bmm_block_content = bmm_gen_block_html($bmm);
      variable_set('bmm_block_content', $bmm_block_content['html']);
      variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
    }
  } else {
      $bmm_block_content = bmm_gen_block_html($bmm);
      variable_set('bmm_block_content', $bmm_block_content['html']);
      variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
  }
}

/**
 * Gets called after a node has been deleted from database.
 *
 * @param $node
 *   A node object
 *
 * @see hook_node_postsave()
 * @see hook_node_postinsert()
 * @see hook_node_postupdate()
 * @see hook_node_postdelete()
 */
function hook_post_action_bmm_node_postdelete($node) {
  $bmm = variable_get('bmm_menu', '');

  $bmm_block_content = bmm_gen_block_html($bmm);
  variable_set('bmm_block_content', $bmm_block_content['html']);
  variable_set('bmm_mobile_block_content', $bmm_block_content['mobile']);
}
